### PR TITLE
#418. Added animations and customizer toggle for animations.

### PR DESCRIPTION
**Pull request by abaicus**
@rodica-andronache we still have to add them to the pro plugin.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@abaicus 

- [ ] Please change paralax_one_enable_animations to parallax_one_enable_animations to try to mantain the same name ( even though there are some options with just paralax )

- [ ] in some places, you are calling get_theme_mod(paralax_one_enable_animations)  with a default value, in other places, without a default value. and when the setting is defined it doesn't have a default value defined. The code should be consistent, with a default value or not 

- [ ] i'm not sure this two checks are necessary, could you please check http://prntscr.com/csyuzq ? From what I know empty already considers 0 as empty so, maybe , the second condition would not be necessary, but you would need to test http://stackoverflow.com/questions/7191626/isset-and-empty-what-to-use

- [ ] you should also mention the license for the new script used scrollReveal.js in readme.md

- [ ] I think here you've missed some semicolons http://prntscr.com/csz107

- [ ] at the end, you can also have a look again, in case I missed something :)

thanks

**Comment by abaicus** [comment]
@rodica-andronache

**Comment by rodica-andronache** [comment]
@abaicus thanks. Just some small changes :)

- [ ] In scrollReveal.js please close this comment  http://prntscr.com/ct8xgz . we had this issue reported for zerif. It was causing issues with minifiation plugins

- [ ] when declaring the default value, maybe it should be a string? I'm not sure, but when you get the option from customizer, you get it as a string, not integer. Can you please check? Also, can you change the label or the description to say the same , either frontpage or homepage? http://prntscr.com/ct8yga

**Comment by abaicus** [comment]
@rodica-andronache done! 👍

**Pull request merged**
