### PR TITLE
Recommend our own contact form plugin

### PR DESCRIPTION
**Pull request by UVLabs**
Since we now have a contact form plugin I believe it's best to recommend it rather than a 3rd party one. I also made URLs for contact form plugin and maps plugin open in a new tab for UX reasons so users don't accidentally get off customizer if checking out the recommended plugins.

### CODE REVIEW

**Comment by ineagu** [comment]
Ideally you would also mention @rodica-andronache , so she knows about the pull :)

**Comment by UVLabs** [comment]
Yes sorry about that, thank you :)

**Comment by rodica-andronache** [comment]
Hi @UVLabs ,

Thanks! For future contributions, just wanted to mention that we usually have one commit for each of the issues we solve. In this case, you could have made 2 commits, one for replacing the recommended plugin and one for updating the po and mo files. It's easier this way to manage all the issues.
Also, when you fix a issue that is not very relevant for the user, you can prefix you commit message with !!! . This way, that commit will not appear in the changelog of the theme. You can see previous commits to see what I mean.

Again, this is just something that we use (not all the time :D ) and wanted to let you know, please don't feel discouraged in any way or something like that :)

Rodica

**Comment by UVLabs** [comment]
Thanks @rodica-andronache now I know the codeinwp standard :)

**Pull request merged**
